name: celmech (ipynb)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest matplotlib scipy 
          pip install wheel setuptools
      - name: Install Celmech 
        run: |
          pip install -e . -v 
      - name: Running jupyter notebooks
        run: |
          cd jupyter_examples
          python ipynb2py.py QuickstartExample.ipynb
